version: '3'

services:
  otel-collector:
    image: otel/opentelemetry-collector:0.61.0
    command:
      - "--config=/etc/otel-collector.yaml"
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
