version: '3'

services:
  otel-collector:
    image: otel/opentelemetry-collector:0.82.0
    command:
      - "--config=/etc/otel-collector.yaml"
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml

  tempo:
    image: grafana/tempo:latest
    command:
      - "-config.file=/etc/tempo.yaml"
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - 3200:3200
      - 4317:4317

  grafana:
    image: grafana/grafana:9.3.6-ubuntu
    ports:
      - 3000:3000
